FROM node:20 as build
WORKDIR /app
COPY /quokka_editor_front/package.json .
RUN npm install
COPY /quokka_editor_front .
RUN npm run build

FROM nginx:1.24
COPY --from=build /app/dist /usr/share/nginx/html
